services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: example
      DB_NAME: purchasing_db
  db:
    image: mysql:8.0
    container_name: purchasing-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: purchasing_db
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
