# Gunakan image Node.js resmi sebagai base image
FROM node:18

# Set direktori kerja di dalam container
WORKDIR /app

# Salin file package.json dan package-lock.json ke container
COPY package*.json ./

# Instal semua dependencies
RUN npm install

# Salin semua file proyek Anda ke dalam container
COPY . .

# Ekspos port 3000 (port aplikasi Anda berjalan)
EXPOSE 3000

# Perintah untuk menjalankan aplikasi
CMD ["node", "app.js"]
